### ISSUE TITLE
Generate HTML directly with xsltproc

### ISSUE THREAD

**Issue by slavkoja** [Matter-Tech/dmarc-xslt#1]
Not issue, but tip, instead manipulating the XML with ``sed``, you can directly transform it to HTML with ``xsltproc``, eg. with:
```
7z e report.xml.gz -so | xmllint --format - | xsltproc -o report.html dmarc.xslt -
```
Apply filename logic as you want...

**Comment by aksel** [comment]
Cool! Thanks for the tip :smile:
