### ISSUE TITLE
Multiple DKIM signatures

### ISSUE THREAD

**Issue by slavkoja** [Matter-Tech/dmarc-xslt#2]
I am using dual DKIM sign (RSA & ED25519), thus some of reports i am getting with multiple DKIM fields, eg:
```xml
<auth_results>
  <dkim>
    <domain>domain.tld</domain>
    <result>pass</result>
    <selector>sel1</selector>
  </dkim>
  <dkim>
    <domain>domain.tld</domain>
    <result>fail</result>
    <selector>sel2</selector>
  </dkim>
  <spf>
    <domain>domain.tld</domain>
    <result>fail</result>
  </spf>
</auth_results>
```
But your XSLT doesn't count the second one, only the first is shown. The DMARC XML schema defines zero to unlimited DKIM records and one to unlimited SPF records for ``auth_results``.

Please can you improve the XSLT to show list (``ul``) of these results?

**Comment by aksel** [comment]
Hey! Sorry, I've been quite busy at work the last couple of weeks. I'll try to take a look at this tomorrow :smile: 

Happy to see someone's using this :ok_hand:

**Comment by slavkoja** [comment]
> Hey! Sorry, I've been quite busy at work the last couple of weeks.

No problem ;-)

I implemented it by self. To be honest i did a lot of changes in your XSLT, but problem is, that i am no very familiar with XSLT thus my modification are mostly compilation of examples which i found over net and i am not sure, if i am doing it properly. But at least one i will share (in separate bugreport).

> Happy to see someone's using this

I implemented it by own way. My MTA (exim) is extracting XML from reports and storing it in particular place, from where it is accessible via web (nginx), which does XSL transformation directly by its module. Thus clicking on XML directly shows transformed HTML. It is great solution for my small email system (which do not sends a lot of emails).

I even send copy of my reports here, to i can better see what is happening on incoming side.

**Comment by aksel** [comment]
Sorry for the radio silence from me! I've still been very busy with work.

But I implemented this yesterday evening. I did this while aboard an overnight train without internet, so I messed up the styling itself (colors and such).

But now all auth results will show up :smile:

**Comment by aksel** [comment]
I've fixed the styling. The XSLT is now hosted at `https://statis.thisismatter.com/dmarc-xslt/dmarc.xslt`.
